all:
	g++ -o jambo-tubos jambo-tubos.cpp -O2 -std=c++14
test:
	g++ -o test-jambo-tubos jambo-tubos-tester.cpp -O2 -std=c++14
clean:
	rm -f $(OBJS)
	rm -f $(EXE)
	rm -f *.o
	rm -f jambo-tubos test-jambo-tubos